# Rename Specific Column name

In [1]:
import pandas as pd

In [2]:
my_list = [
    {"name" : "Raj","age": 10, "std" :2},
    {"name" : "Sahil","age": 10, "std" :2},
    {"name" : "Rahul","age": 10, "std" :2}
]
df = pd.DataFrame(my_list)
print(df)

    name  age  std
0    Raj   10    2
1  Sahil   10    2
2  Rahul   10    2

In [3]:
df.rename(columns={"std" : "standard"},inplace=True)

In [4]:
print(df)

    name  age  standard
0    Raj   10         2
1  Sahil   10         2
2  Rahul   10         2

## Read and Write :

### 1. CSV File:

### Write :

In [5]:
df.to_csv("csvfile.csv",index=False)

In [6]:
df.to_csv("csvfile2.csv",index=True)

### Read :

In [7]:
print(pd.read_csv("csvfile.csv"))

    name  age  standard
0    Raj   10         2
1  Sahil   10         2
2  Rahul   10         2

In [8]:
print(pd.read_csv("csvfile2.csv"))

   Unnamed: 0   name  age  standard
0           0    Raj   10         2
1           1  Sahil   10         2
2           2  Rahul   10         2

### 2. JSON File :

### Write :

In [9]:
df.to_json("myjson1.json")

### Read :

In [10]:
pd.read_json("myjson1.json")

    name  age  standard
0    Raj   10         2
1  Sahil   10         2
2  Rahul   10         2

### 3. Excel File:

### Write :

In [16]:
df.to_excel("myexcel.xlsx",index=False)

### Read :

In [17]:
pd.read_excel("myexcel.xlsx")

    name  age  standard
0    Raj   10         2
1  Sahil   10         2
2  Rahul   10         2

## Handle missing values:

In [35]:
my_list = [
    {"name" : "Raj","age": 23, "std" :2},
    {"name" : "Sahil","age": 10, "std" :2},
    {"name" : "Rahul","age": 10, "std" :4}
]
df = pd.DataFrame(my_list)
print(df)

    name  age  std
0    Raj   23    2
1  Sahil   10    2
2  Rahul   10    4

In [19]:
df.isnull()

    name    age    std
0  False   True  False
1  False  False  False
2  False  False   True

<bound method DataFrame.sum of     name    age    std
0  False   True  False
1  False  False  False
2  False  False   True>

In [22]:
print(df.isnull().sum())

name    0
age     1
std     1
dtype: int64

In [23]:
df.dropna()

    name   age  std
1  Sahil  10.0  2.0

In [24]:
df

    name   age  std
0    Raj   NaN  2.0
1  Sahil  10.0  2.0
2  Rahul  10.0  NaN

### duplicates :

In [28]:
print(df.duplicated("age"))

0    False
1    False
2     True
dtype: bool

In [31]:
df.drop_duplicates("std")

    name   age  std
0    Raj   NaN  2.0
2  Rahul  10.0  NaN

In [32]:
df.dtypes

name        str
age     float64
std     float64
dtype: object

In [38]:
df["age"] = df["age"].astype("str")

In [39]:
df.dtypes

name      str
age       str
std     int64
dtype: object

In [40]:
employees = [
    {"name": "Rahul Sharma", "employee_id": "EMP001", "joining_date": "2024-01-10"},
    {"name": "Priya Patel", "employee_id": "EMP002", "joining_date": "2024-02-15"},
    {"name": "Amit Shah", "employee_id": "EMP003", "joining_date": "2024-03-05"},
    {"name": "Neha Mehta", "employee_id": "EMP004", "joining_date": "2024-04-20"},
    {"name": "Rohan Desai", "employee_id": "EMP005", "joining_date": "2024-05-12"}
]

In [41]:
df = pd.DataFrame(employees)

In [42]:
df

           name employee_id joining_date
0  Rahul Sharma      EMP001   2024-01-10
1   Priya Patel      EMP002   2024-02-15
2     Amit Shah      EMP003   2024-03-05
3    Neha Mehta      EMP004   2024-04-20
4   Rohan Desai      EMP005   2024-05-12

In [43]:
df.dtypes

name            str
employee_id     str
joining_date    str
dtype: object

In [44]:
df["joining_date"] = df["joining_date"].astype("datetime64[ms, UTC]")

In [45]:
df.dtypes

name                            str
employee_id                     str
joining_date    datetime64[ms, UTC]
dtype: object

In [46]:
pd.DatetimeIndex(df["joining_date"])

DatetimeIndex(['2024-01-10 00:00:00+00:00', '2024-02-15 00:00:00+00:00',
               '2024-03-05 00:00:00+00:00', '2024-04-20 00:00:00+00:00',
               '2024-05-12 00:00:00+00:00'],
              dtype='datetime64[ms, UTC]', name='joining_date', freq=None)

In [47]:
import datetime

In [48]:
datetime.datetime.now()

datetime.datetime(2026, 9, 24, 10, 52, 16, 644511)

In [49]:
datetime.datetime.today()

datetime.datetime(2026, 9, 24, 10, 52, 28, 772433)