In [ ]:
import pandas as pd

In [ ]:
sf = pd.Series([11,12,1,32,14])

In [ ]:
print(sf)

In [ ]:
print(sf.loc[0])
print(sf.iloc[1])

# Creation of DataFrames:

In [ ]:
# 1. List of List 
my_list = [
    ["Raj",10,2],
    ["Sahil",20,4],
    ["Rahul",30,5]
]
df1 = pd.DataFrame(my_list,columns=["name","age","std"])
print(df1)

In [ ]:
# 2. Dict 
my_dict = {
    "name" : ["Raj","Sahil","Rahul"],
    "age" : [10,23,43],
    "std" : [2,3,4]
}
df2 = pd.DataFrame(my_dict)
print(df2)

In [ ]:
# 3. List of Dict
my_list = [
    {"name" : "Raj","age": 10, "std" :2},
    {"name" : "Sahil","age": 10, "std" :2},
    {"name" : "Rahul","age": 10, "std" :2}
]
df3 = pd.DataFrame(my_list,index=["@","!","%"])
print(df3)

In [ ]:
print(df3.loc["@"])

In [ ]:
print(df3.iloc[0])

In [ ]:
# Exploring Data (Series and DataFrame)
# Operations on DataFrames

In [1]:
import pandas as pd

In [15]:
sf  = pd.Series([11,23,67,45,87,23,11])

In [16]:
print(sf)

0    11
1    23
2    67
3    45
4    87
5    23
6    11
dtype: int64

In [10]:
print(sf.loc["value1"])     # label 
print(sf.iloc[0])    # index

11
11

In [ ]:
print(sf.loc["value1":"value3"])
print()
print(sf.iloc[0:3])

value1    11
value2    23
value3    67
dtype: int64

value1    11
value2    23
value3    67
dtype: int64

In [20]:
print(sf.head())

0    11
1    23
2    67
3    45
4    87
dtype: int64

In [22]:
print(sf.head(2))

0    11
1    23
dtype: int64

In [24]:
print(sf.tail())

2    67
3    45
4    87
5    23
6    11
dtype: int64

In [25]:
print(sf.tail(1))

6    11
dtype: int64

In [26]:
print(sf.index)

RangeIndex(start=0, stop=7, step=1)

In [27]:
print(sf.sort_values())

0    11
6    11
5    23
1    23
3    45
2    67
4    87
dtype: int64

In [29]:
print(sf.sort_values(ascending=False))

4    87
2    67
3    45
5    23
1    23
0    11
6    11
dtype: int64

In [32]:
print(sf[3])

100

In [31]:
sf[3] = 100

In [33]:
sf.drop(1)

0     11
2     67
3    100
4     87
5     23
6     11
dtype: int64

In [50]:
# DataFrame 
my_dict = {
    "name": [
        "Raj", "Sahil", "Rahul", "Amit", "Priya",
        "Neha", "Rohan", "Karan", "Pooja", "Vikas",
        "Anjali", "Harsh", "Sneha", "Yash", "Riya",
        "Dhruv", "Kavya", "Manav", "Isha", "Nikhil"
    ],

    "age": [
        None, 19, 20, 18, 19,
        20, 18, 21, 19, 20,
        18, 21, 19, 20, 18,
        19, 20, 21, 18, 19
    ],

    "std": [
        12, 12, 11, 10, 12,
        11, 10, 12, 11, 10,
        12, 11, 10, 12, 11,
        10, 12, 11, 10, 12
    ]
}
df = pd.DataFrame(my_dict)
print(df)

      name   age  std
0      Raj   NaN   12
1    Sahil  19.0   12
2    Rahul  20.0   11
3     Amit  18.0   10
4    Priya  19.0   12
5     Neha  20.0   11
6    Rohan  18.0   10
7    Karan  21.0   12
8    Pooja  19.0   11
9    Vikas  20.0   10
10  Anjali  18.0   12
11   Harsh  21.0   11
12   Sneha  19.0   10
13    Yash  20.0   12
14    Riya  18.0   11
15   Dhruv  19.0   10
16   Kavya  20.0   12
17   Manav  21.0   11
18    Isha  18.0   10
19  Nikhil  19.0   12

In [ ]:
print(df.loc[1])

name    Sahil
age        23
std         3
Name: 1, dtype: object

In [37]:
print(df.loc[1:])

    name  age  std
1  Sahil   23    3
2  Rahul   43    4

In [39]:
print(df.iloc[0])

name    Raj
age      10
std       2
Name: 0, dtype: object

In [40]:
print(df.iloc[0:1])

  name  age  std
0  Raj   10    2

In [42]:
print(df)

      name  age  std
0      Raj   18   12
1    Sahil   19   12
2    Rahul   20   11
3     Amit   18   10
4    Priya   19   12
5     Neha   20   11
6    Rohan   18   10
7    Karan   21   12
8    Pooja   19   11
9    Vikas   20   10
10  Anjali   18   12
11   Harsh   21   11
12   Sneha   19   10
13    Yash   20   12
14    Riya   18   11
15   Dhruv   19   10
16   Kavya   20   12
17   Manav   21   11
18    Isha   18   10
19  Nikhil   19   12

In [43]:
print(df.head())

    name  age  std
0    Raj   18   12
1  Sahil   19   12
2  Rahul   20   11
3   Amit   18   10
4  Priya   19   12

In [44]:
print(df.head(3))

    name  age  std
0    Raj   18   12
1  Sahil   19   12
2  Rahul   20   11

In [45]:
print(df.tail())

      name  age  std
15   Dhruv   19   10
16   Kavya   20   12
17   Manav   21   11
18    Isha   18   10
19  Nikhil   19   12

In [46]:
print(df.tail(2))

      name  age  std
18    Isha   18   10
19  Nikhil   19   12

In [47]:
print(df.index)

RangeIndex(start=0, stop=20, step=1)

In [48]:
print(df.columns)

Index(['name', 'age', 'std'], dtype='str')

In [51]:
print(df)

      name   age  std
0      Raj   NaN   12
1    Sahil  19.0   12
2    Rahul  20.0   11
3     Amit  18.0   10
4    Priya  19.0   12
5     Neha  20.0   11
6    Rohan  18.0   10
7    Karan  21.0   12
8    Pooja  19.0   11
9    Vikas  20.0   10
10  Anjali  18.0   12
11   Harsh  21.0   11
12   Sneha  19.0   10
13    Yash  20.0   12
14    Riya  18.0   11
15   Dhruv  19.0   10
16   Kavya  20.0   12
17   Manav  21.0   11
18    Isha  18.0   10
19  Nikhil  19.0   12

In [53]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    20 non-null     str
 1   age     19 non-null     float64
 2   std     20 non-null     int64
dtypes: float64(1), int64(1), str(1)
memory usage: 612.0 bytes

In [54]:
df.describe()

             age        std
count  19.000000  20.000000
mean   19.315789  11.100000
std     1.056863   0.852242
min    18.000000  10.000000
25%    18.500000  10.000000
50%    19.000000  11.000000
75%    20.000000  12.000000
max    21.000000  12.000000

In [55]:
df.drop(1)

      name   age  std
0      Raj   NaN   12
2    Rahul  20.0   11
3     Amit  18.0   10
4    Priya  19.0   12
5     Neha  20.0   11
6    Rohan  18.0   10
7    Karan  21.0   12
8    Pooja  19.0   11
9    Vikas  20.0   10
10  Anjali  18.0   12
11   Harsh  21.0   11
12   Sneha  19.0   10
13    Yash  20.0   12
14    Riya  18.0   11
15   Dhruv  19.0   10
16   Kavya  20.0   12
17   Manav  21.0   11
18    Isha  18.0   10
19  Nikhil  19.0   12

In [56]:
print(df["name"])

0        Raj
1      Sahil
2      Rahul
3       Amit
4      Priya
5       Neha
6      Rohan
7      Karan
8      Pooja
9      Vikas
10    Anjali
11     Harsh
12     Sneha
13      Yash
14      Riya
15     Dhruv
16     Kavya
17     Manav
18      Isha
19    Nikhil
Name: name, dtype: str

In [57]:
df["std"] = 13

In [58]:
print(df)

      name   age  std
0      Raj   NaN   13
1    Sahil  19.0   13
2    Rahul  20.0   13
3     Amit  18.0   13
4    Priya  19.0   13
5     Neha  20.0   13
6    Rohan  18.0   13
7    Karan  21.0   13
8    Pooja  19.0   13
9    Vikas  20.0   13
10  Anjali  18.0   13
11   Harsh  21.0   13
12   Sneha  19.0   13
13    Yash  20.0   13
14    Riya  18.0   13
15   Dhruv  19.0   13
16   Kavya  20.0   13
17   Manav  21.0   13
18    Isha  18.0   13
19  Nikhil  19.0   13

In [60]:
df["std"] = [11,12,4,5,6,11,12,4,5,6,11,12,4,5,6,11,12,4,5,6]

In [61]:
print(df)

      name   age  std
0      Raj   NaN   11
1    Sahil  19.0   12
2    Rahul  20.0    4
3     Amit  18.0    5
4    Priya  19.0    6
5     Neha  20.0   11
6    Rohan  18.0   12
7    Karan  21.0    4
8    Pooja  19.0    5
9    Vikas  20.0    6
10  Anjali  18.0   11
11   Harsh  21.0   12
12   Sneha  19.0    4
13    Yash  20.0    5
14    Riya  18.0    6
15   Dhruv  19.0   11
16   Kavya  20.0   12
17   Manav  21.0    4
18    Isha  18.0    5
19  Nikhil  19.0    6

In [62]:
df["marks"] = 0

In [63]:
print(df)

      name   age  std  marks
0      Raj   NaN   11      0
1    Sahil  19.0   12      0
2    Rahul  20.0    4      0
3     Amit  18.0    5      0
4    Priya  19.0    6      0
5     Neha  20.0   11      0
6    Rohan  18.0   12      0
7    Karan  21.0    4      0
8    Pooja  19.0    5      0
9    Vikas  20.0    6      0
10  Anjali  18.0   11      0
11   Harsh  21.0   12      0
12   Sneha  19.0    4      0
13    Yash  20.0    5      0
14    Riya  18.0    6      0
15   Dhruv  19.0   11      0
16   Kavya  20.0   12      0
17   Manav  21.0    4      0
18    Isha  18.0    5      0
19  Nikhil  19.0    6      0

In [65]:
df.drop(1)

      name   age  std  marks
0      Raj   NaN   11      0
2    Rahul  20.0    4      0
3     Amit  18.0    5      0
4    Priya  19.0    6      0
5     Neha  20.0   11      0
6    Rohan  18.0   12      0
7    Karan  21.0    4      0
8    Pooja  19.0    5      0
9    Vikas  20.0    6      0
10  Anjali  18.0   11      0
11   Harsh  21.0   12      0
12   Sneha  19.0    4      0
13    Yash  20.0    5      0
14    Riya  18.0    6      0
15   Dhruv  19.0   11      0
16   Kavya  20.0   12      0
17   Manav  21.0    4      0
18    Isha  18.0    5      0
19  Nikhil  19.0    6      0

In [68]:
df.drop("marks",axis=1,inplace=True)

In [69]:
print(df)

      name   age  std
0      Raj   NaN   11
1    Sahil  19.0   12
2    Rahul  20.0    4
3     Amit  18.0    5
4    Priya  19.0    6
5     Neha  20.0   11
6    Rohan  18.0   12
7    Karan  21.0    4
8    Pooja  19.0    5
9    Vikas  20.0    6
10  Anjali  18.0   11
11   Harsh  21.0   12
12   Sneha  19.0    4
13    Yash  20.0    5
14    Riya  18.0    6
15   Dhruv  19.0   11
16   Kavya  20.0   12
17   Manav  21.0    4
18    Isha  18.0    5
19  Nikhil  19.0    6

In [70]:
sf = pd.Series([11,12,13,14])

In [71]:
sf

0    11
1    12
2    13
3    14
dtype: int64

In [72]:
sf + 10

0    21
1    22
2    23
3    24
dtype: int64

In [73]:
sf * 2

0    22
1    24
2    26
3    28
dtype: int64

In [74]:
print(sf[ sf >12 ])

2    13
3    14
dtype: int64

In [75]:
print(sf > 12)

0    False
1    False
2     True
3     True
dtype: bool

In [77]:
df

      name   age  std
0      Raj   NaN   11
1    Sahil  19.0   12
2    Rahul  20.0    4
3     Amit  18.0    5
4    Priya  19.0    6
5     Neha  20.0   11
6    Rohan  18.0   12
7    Karan  21.0    4
8    Pooja  19.0    5
9    Vikas  20.0    6
10  Anjali  18.0   11
11   Harsh  21.0   12
12   Sneha  19.0    4
13    Yash  20.0    5
14    Riya  18.0    6
15   Dhruv  19.0   11
16   Kavya  20.0   12
17   Manav  21.0    4
18    Isha  18.0    5
19  Nikhil  19.0    6

In [78]:
df["std"] - 1

0     10
1     11
2      3
3      4
4      5
5     10
6     11
7      3
8      4
9      5
10    10
11    11
12     3
13     4
14     5
15    10
16    11
17     3
18     4
19     5
Name: std, dtype: int64

In [79]:
df

      name   age  std
0      Raj   NaN   11
1    Sahil  19.0   12
2    Rahul  20.0    4
3     Amit  18.0    5
4    Priya  19.0    6
5     Neha  20.0   11
6    Rohan  18.0   12
7    Karan  21.0    4
8    Pooja  19.0    5
9    Vikas  20.0    6
10  Anjali  18.0   11
11   Harsh  21.0   12
12   Sneha  19.0    4
13    Yash  20.0    5
14    Riya  18.0    6
15   Dhruv  19.0   11
16   Kavya  20.0   12
17   Manav  21.0    4
18    Isha  18.0    5
19  Nikhil  19.0    6

In [80]:
df["std"] > 8

0      True
1      True
2     False
3     False
4     False
5      True
6      True
7     False
8     False
9     False
10     True
11     True
12    False
13    False
14    False
15     True
16     True
17    False
18    False
19    False
Name: std, dtype: bool

In [81]:
print(df[ df["std"] > 8])

      name   age  std
0      Raj   NaN   11
1    Sahil  19.0   12
5     Neha  20.0   11
6    Rohan  18.0   12
10  Anjali  18.0   11
11   Harsh  21.0   12
15   Dhruv  19.0   11
16   Kavya  20.0   12

In [ ]:
df.sort_values(["std"])

      name   age  std
2    Rahul  20.0    4
7    Karan  21.0    4
12   Sneha  19.0    4
17   Manav  21.0    4
8    Pooja  19.0    5
13    Yash  20.0    5
18    Isha  18.0    5
3     Amit  18.0    5
14    Riya  18.0    6
19  Nikhil  19.0    6
9    Vikas  20.0    6
4    Priya  19.0    6
15   Dhruv  19.0   11
10  Anjali  18.0   11
0      Raj   NaN   11
5     Neha  20.0   11
11   Harsh  21.0   12
6    Rohan  18.0   12
1    Sahil  19.0   12
16   Kavya  20.0   12