In [ ]:
import pandas as pd

In [ ]:
my_dict = {
    "Name": ["Raj", "Sahil", "Rahul", "Amit", "Neha"],
    "Age": [22, 23, 21, 25, 22],
    "City": ["Rajkot", "Ahmedabad", "Surat", "Rajkot", "Ahmedabad"],
    "Marks": [85, 72, 90, 65, 88]
}

df = pd.DataFrame(my_dict)

In [ ]:
df

## 1. data Sorting

In [ ]:
df.sort_values("Marks")  # asc

In [ ]:
df.sort_values("Marks",ascending=False)

In [ ]:
df.sort_values("Age")

In [ ]:
df.sort_values("Age",ascending=False)

In [ ]:
df.sort_values(["Age"])

In [ ]:
df.sort_values(["Age","Marks"])

In [ ]:
df.sort_values(["Age","Marks"],ascending=False)

## 2. data Filtering

In [ ]:
df

In [ ]:
df["Marks"] > 85

In [ ]:
df[df["Marks"] > 85]

In [ ]:
df[df["Marks"] > 85 ]

In [ ]:
df.where(df["Age"] < 22)

In [ ]:
result = df[df["Marks"] > 85]

In [ ]:
result

In [ ]:
result[result["Age"] < 22]

## 3. Data Aggregation:

In [ ]:
my_dict = {
    "Name": ["Raj", "Sahil", "Rahul", "Amit", "Neha"],
    "Age": [22, 23, 21, 25, 22],
    "City": ["Rajkot", "Ahmedabad", "Surat", "Rajkot", "Ahmedabad"],
    "Marks": [85, 72, 90, 65, 88]
}

df = pd.DataFrame(my_dict)

In [ ]:
df

In [ ]:
# df["Marks"].min
# df["Marks"].max 
# df["Marks"].median
# df["Marks"].mod

# df["Marks"].agg

In [ ]:
df["Marks"].min()

In [ ]:
df["Marks"].max()

In [ ]:
df["Marks"].median()

In [ ]:
df["Age"].mod(23)

In [ ]:
df["Marks"].agg(["min"])

In [ ]:
df["Marks"].agg(["min","max"])

In [ ]:
df["Marks"].agg(["min","max","mean"])

In [ ]:
# df["Marks"].agg(["min","max","mean"])

In [61]:
my_dict = {
        'Store': ['North', 'South', 'North', 'West', 'South', 'West'],
    'Product': ['Apples', 'Bananas', 'Apples', 'Bananas', 'Apples', 'Bananas'],
    'Sales': [100, 150, 200, 300, 120, 250],
    'Quantity': [10, 15, 20, 30, 12, 25]
}

df = pd.DataFrame(my_dict)

In [62]:
df

   Store  Product  Sales  Quantity
0  North   Apples    100        10
1  South  Bananas    150        15
2  North   Apples    200        20
3   West  Bananas    300        30
4  South   Apples    120        12
5   West  Bananas    250        25

In [58]:
df.groupby("City")["City"].count()

City
Ahmedabad    2
Rajkot       2
Surat        1
Name: City, dtype: int64

In [63]:
df.groupby("Store")["Product"].sum()

Store
North      ApplesApples
South     BananasApples
West     BananasBananas
Name: Product, dtype: str

In [64]:
df.groupby("Store")["Product"].count()

Store
North    2
South    2
West     2
Name: Product, dtype: int64

## Marge :

In [66]:
df1 = pd.DataFrame(
    {
        "Id" : [1,2,3],
        "Name" : ["Raj","Sahil","Rajesh"]
    })

df2 = pd.DataFrame(
    {
        "Id" : [1,2,3],
        "Marks" : [67,89,45],
        "Age" : [12,23,16]
    })

In [67]:
df1

   Id    Name
0   1     Raj
1   2   Sahil
2   3  Rajesh

In [68]:
df2

   Id  Marks  Age
0   1     67   12
1   2     89   23
2   3     45   16

In [70]:
newdf = pd.merge(df1,df2)
newdf

   Id    Name  Marks  Age
0   1     Raj     67   12
1   2   Sahil     89   23
2   3  Rajesh     45   16

In [71]:
newdf = pd.merge(df1,df2,how="inner")
newdf

   Id    Name  Marks  Age
0   1     Raj     67   12
1   2   Sahil     89   23
2   3  Rajesh     45   16

In [72]:
newdf = pd.merge(df1,df2,how="outer")
newdf

   Id    Name  Marks  Age
0   1     Raj     67   12
1   2   Sahil     89   23
2   3  Rajesh     45   16

In [73]:
newdf = pd.merge(df1,df2,how="left")
newdf

   Id    Name  Marks  Age
0   1     Raj     67   12
1   2   Sahil     89   23
2   3  Rajesh     45   16

In [76]:

df1.join(df2,on="Id")

ValueError: columns overlap but no suffix specified: Index(['Id'], dtype='str')