In [ ]:
import pandas as pd

In [ ]:
df = pd.DataFrame({
    "name" : ["Raj","Rahul","Sahil","Krutarth","Ramesh"],
    "department" : ["IT","HR","HR","IT","HR"],
    "salary" : [20000,40000,50000,25000,42000]
},index=["A","B","C","D","E"])

In [ ]:
df

In [ ]:
df.index

In [ ]:
df

In [ ]:
new_order = ["D","E","C","A","B"]
df.reindex(new_order)

In [ ]:
df.rename(columns={
    "name" : "FirstName"
})

In [ ]:
df

In [ ]:
df.rename(index={
    "A" : "101"
})   # row

In [ ]:
# Groupby()  :

df

In [ ]:
df.groupby("department")

In [ ]:
df.groupby("department")["salary"].sum()

In [ ]:
df.groupby("department")["salary"].min()

In [ ]:
df.groupby("department")["salary"].max()

In [ ]:
df.groupby("department")["salary"].count()

In [ ]:
df.groupby("department")["salary"].agg(["sum"])

In [ ]:
df.groupby("department")["salary"].agg(["sum","min","max","count"])

In [ ]:
df.groupby("department")["salary"].agg(["count"])

In [ ]:
df.groupby("department")["name"].agg(["count"])

In [31]:
df

       name department  salary
A       Raj         IT   20000
B     Rahul         HR   40000
C     Sahil         HR   50000
D  Krutarth         IT   25000
E    Ramesh         HR   42000

In [32]:
df.groupby("department")["salary"].agg(["sum"])

               sum
department
HR          132000
IT           45000

In [39]:
output =  df.groupby("department")["sal"+"ary"].transform("sum")

In [36]:
output

A     45000
B    132000
C    132000
D     45000
E    132000
Name: salary, dtype: int64

In [40]:
## Join

In [52]:
df1 = pd.DataFrame({
    "id" : [1,2,3],
    "name" : ["Raj","Rahul","Ramesh"]
})

df2 = pd.DataFrame({
    "marks" : [67,90,56],
    "age" : [12,14,13]
},index=[1,2,"C"])

In [53]:
df1

   id    name
0   1     Raj
1   2   Rahul
2   3  Ramesh

In [54]:
df2

   marks  age
1     67   12
2     90   14
C     56   13

In [48]:
df1.join(df2)

   id    name  marks  age
0   1     Raj    NaN  NaN
1   2   Rahul    NaN  NaN
2   3  Ramesh    NaN  NaN

In [ ]:
#   inner,outer ,left(default),right

# join : index (always)
# merge: (identity)
# pd.merge(df1,df2,on="",how=)

df1.join(df2,how="left")

   id    name  marks  age
0   1     Raj    NaN  NaN
1   2   Rahul    NaN  NaN
2   3  Ramesh    NaN  NaN

In [51]:
df1.index

RangeIndex(start=0, stop=3, step=1)

In [55]:
df1.join(df2)

   id    name  marks   age
0   1     Raj    NaN   NaN
1   2   Rahul   67.0  12.0
2   3  Ramesh   90.0  14.0

In [56]:
df1.join(df2,how="left")

   id    name  marks   age
0   1     Raj    NaN   NaN
1   2   Rahul   67.0  12.0
2   3  Ramesh   90.0  14.0

In [57]:
df1.join(df2,how="right")

    id    name  marks  age
1  2.0   Rahul     67   12
2  3.0  Ramesh     90   14
C  NaN     NaN     56   13

In [58]:
df1.join(df2,how="inner")

   id    name  marks  age
1   2   Rahul     67   12
2   3  Ramesh     90   14

In [59]:
df1.join(df2,how="outer")

    id    name  marks   age
0  1.0     Raj    NaN   NaN
1  2.0   Rahul   67.0  12.0
2  3.0  Ramesh   90.0  14.0
C  NaN     NaN   56.0  13.0

In [ ]:
pd.merge